### ISSUE TITLE
CSS selector prefix for generated css

### ISSUE THREAD

**Issue by 0xApp** [madskristensen/ImageSprites#1]
### Installed product versions
- Visual Studio: [example 2015 Community Update 2]
- This extension: [example  1.0.10]
### Description

Option to added css prefix. So that generated output files looks something like this

```
.mylogos {
    background-image: url(spritesheet.png);
    background-repeat: no-repeat;
    display: block;
}

.mylogos-github {
    width: 30px;
    height: 30px;
    background-position: -2px -2px;
}

.mylogos-gmail {
    width: 30px;
    height: 30px;
    background-position: -36px -2px;
}
```

**Comment by madskristensen** [comment]
This would make it look a bit like Bootstrap (glyphicons) and a lot of people are familiar with that. It should do this by default instead of it being an option, don't you think?

**Comment by 0xApp** [comment]
Yes, this should be the default.

**Comment by 0xApp** [comment]
I would say that for myfile.sprite the default prefix should be myfile

**Comment by madskristensen** [comment]
Agreed. This is what it does now. Can you try the latest [CI build](http://vsixgallery.com/extension/cd92c0c6-2c32-49a3-83ca-0dc767c7d78e/) and let me know if it works as expected?

**Comment by 0xApp** [comment]
Yes! It is working as expected!

**Thank You so much for such quick work!**
