### ISSUE TITLE
Feature Request: cache invalidation. ex: url(img.sprite.png?v2)

### ISSUE THREAD

**Issue by robrobrobrob** [madskristensen/ImageSprites#6]
### Description
When updating an existing sprite, it would be great to have something in the css/scss/less that forces cache invalidation. Ideally, it would be some sort of checksum and updated automatically. Another option would be a simple pathpostfix (or querystring) option... pathpostfix: '?v2'

**Comment by Driedas** [comment]
Hey,
our team just stumbled across this requirement as well, would you accept a pull request with this feature?

At a glance, I would probably add a `public bool AppendCacheBustSpriteSuffix {get;set;}` into `SpriteDocument` and add a conditional branch to check for this property in `SpriteStylesheetGenerator.cs#L27` to optionally calculate and append the file hash.

**Comment by madskristensen** [comment]
@Driedas Yes, pull requests are always welcome and your suggested approach seems like a great solution.

**Comment by Driedas** [comment]
@madskristensen submitted as PR #7, but the appveyor build is failing to start...

**Comment by madskristensen** [comment]
I know what is causing it and it has nothing to do with your PR. I'm on it!

**Comment by madskristensen** [comment]
Fixed
